version: "3.9"

services:
  backend:
    build:
      context: ./backend
    command: poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./backend/.env.example
    volumes:
      - ./backend/app:/app/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  frontend-node-modules:
